package com.job.radar.config.statemachine;

import com.job.radar.model.enums.statemachine.event.FormEvent;
import com.job.radar.model.enums.statemachine.state.FormState;
import org.springframework.context.annotation.Configuration;
import org.springframework.statemachine.config.EnableStateMachineFactory;
import org.springframework.statemachine.config.StateMachineConfigurerAdapter;
import org.springframework.statemachine.config.builders.StateMachineStateConfigurer;
import org.springframework.statemachine.config.builders.StateMachineTransitionConfigurer;

@Configuration
@EnableStateMachineFactory(name = "formStateMachine")
public class FormStateMachineConfig extends StateMachineConfigurerAdapter<FormState, FormEvent> {

    @Override
    public void configure(StateMachineStateConfigurer<FormState, FormEvent> states) throws Exception {
        states
                .withStates()
                .initial(FormState.FORM_IDLE)
                .state(FormState.ENTERING_FULL_NAME)
                .state(FormState.ENTERING_EMAIL)
                .state(FormState.ENTERING_PHONE)
                .state(FormState.ENTERING_AGE)
                .state(FormState.ENTERING_CITY)
                .state(FormState.ENTERING_POSITION)
                .state(FormState.ENTERING_EXPERIENCE)
                .state(FormState.ENTERING_SKILLS)
                .state(FormState.ENTERING_SALARY)
                .state(FormState.ENTERING_EMPLOYMENT)
                .state(FormState.ENTERING_EDUCATION)
                .state(FormState.ENTERING_LANGUAGES)
                .state(FormState.ENTERING_PORTFOLIO)
                .state(FormState.ENTERING_ABOUT)
                .state(FormState.CONFIRMING_FORM)
                .end(FormState.FORM_COMPLETED)
                .end(FormState.FORM_CANCELLED);
    }

    @Override
    public void configure(StateMachineTransitionConfigurer<FormState, FormEvent> transitions) throws Exception {
        transitions
            // Старт процесса
            .withExternal()
                .source(FormState.FORM_IDLE).target(FormState.ENTERING_FULL_NAME).event(FormEvent.START_CREATION)
                .and()
            .withExternal()
                .source(FormState.FORM_IDLE).target(FormState.ENTERING_FULL_NAME).event(FormEvent.START_EDITING)
                .and()

            // Основной поток вперед
            .withExternal()
                .source(FormState.ENTERING_FULL_NAME).target(FormState.ENTERING_EMAIL).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EMAIL).target(FormState.ENTERING_PHONE).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PHONE).target(FormState.ENTERING_AGE).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_AGE).target(FormState.ENTERING_CITY).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_CITY).target(FormState.ENTERING_POSITION).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_POSITION).target(FormState.ENTERING_EXPERIENCE).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EXPERIENCE).target(FormState.ENTERING_SKILLS).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SKILLS).target(FormState.ENTERING_SALARY).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SALARY).target(FormState.ENTERING_EMPLOYMENT).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EMPLOYMENT).target(FormState.ENTERING_EDUCATION).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EDUCATION).target(FormState.ENTERING_LANGUAGES).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_LANGUAGES).target(FormState.ENTERING_PORTFOLIO).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PORTFOLIO).target(FormState.ENTERING_ABOUT).event(FormEvent.NEXT)
                .and()
            .withExternal()
                .source(FormState.ENTERING_ABOUT).target(FormState.CONFIRMING_FORM).event(FormEvent.NEXT)
                .and()

            // Назад по шагам
            .withExternal()
                .source(FormState.ENTERING_EMAIL).target(FormState.ENTERING_FULL_NAME).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PHONE).target(FormState.ENTERING_EMAIL).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_AGE).target(FormState.ENTERING_PHONE).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_CITY).target(FormState.ENTERING_AGE).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_POSITION).target(FormState.ENTERING_CITY).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EXPERIENCE).target(FormState.ENTERING_POSITION).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SKILLS).target(FormState.ENTERING_EXPERIENCE).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SALARY).target(FormState.ENTERING_SKILLS).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EMPLOYMENT).target(FormState.ENTERING_SALARY).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EDUCATION).target(FormState.ENTERING_EMPLOYMENT).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_LANGUAGES).target(FormState.ENTERING_EDUCATION).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PORTFOLIO).target(FormState.ENTERING_LANGUAGES).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.ENTERING_ABOUT).target(FormState.ENTERING_PORTFOLIO).event(FormEvent.PREVIOUS)
                .and()
            .withExternal()
                .source(FormState.CONFIRMING_FORM).target(FormState.ENTERING_ABOUT).event(FormEvent.PREVIOUS)
                .and()

            // Пропуск шагов (если поле необязательное)
            .withExternal()
                .source(FormState.ENTERING_PORTFOLIO).target(FormState.ENTERING_ABOUT).event(FormEvent.SKIP)
                .and()
            .withExternal()
                .source(FormState.ENTERING_ABOUT).target(FormState.CONFIRMING_FORM).event(FormEvent.SKIP)
                .and()

            // Подтверждение и редактирование
            .withExternal()
                .source(FormState.CONFIRMING_FORM).target(FormState.FORM_COMPLETED).event(FormEvent.CONFIRM)
                .and()
            .withExternal()
                .source(FormState.CONFIRMING_FORM).target(FormState.ENTERING_FULL_NAME).event(FormEvent.EDIT)
                .and()

            // Отмена из любого состояния
            .withExternal()
                .source(FormState.ENTERING_FULL_NAME).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EMAIL).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PHONE).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_AGE).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_CITY).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_POSITION).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EXPERIENCE).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SKILLS).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_SALARY).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EMPLOYMENT).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_EDUCATION).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_LANGUAGES).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_PORTFOLIO).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.ENTERING_ABOUT).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL)
                .and()
            .withExternal()
                .source(FormState.CONFIRMING_FORM).target(FormState.FORM_CANCELLED).event(FormEvent.CANCEL);
    }
}