package com.job.radar.model.enums.statemachine.state;

public enum FormState {
    FORM_IDLE,
    ENTERING_FULL_NAME,
    ENTERING_EMAIL,
    ENTERING_PHONE,
    ENTERING_AGE,
    ENTERING_CITY,
    ENTERING_POSITION,
    ENTERING_EXPERIENCE,
    ENTERING_SKILLS,
    ENTERING_SALARY,
    ENTERING_EMPLOYMENT,
    ENTERING_EDUCATION,
    ENTERING_LANGUAGES,
    ENTERING_PORTFOLIO,
    ENTERING_ABOUT,
    CONFIRMING_FORM,
    FORM_COMPLETED,
    FORM_CANCELLED
}
